define ICP36_light_gray_0
texture { surface {
  color white
  ambient 0
  diffuse 0.705882
  } }

define ICP36_light_gray_1
texture { surface {
  color white
  ambient 0
  diffuse 0.627451
  } }

define ICP36_dark_gray_2
texture { surface {
  color white
  ambient 0
  diffuse 0.294118
  } }

define ICP36_white_3
texture { surface {
  color white
  ambient 0
  diffuse 1
  } }

define ICP36_black_4
texture { surface {
  color white
  ambient 0
  diffuse 0.0784314
  } }

define ICP36_very_light_gray_5
texture { surface {
  color white
  ambient 0
  diffuse 0.784314
  } }

define ICP36_dark_gray_6
texture { surface {
  color white
  ambient 0
  diffuse 0.313725
  } }

define ICP36_light_gray_7
texture { surface {
  color white
  ambient 0
  diffuse 0.588235
  } }

define ICP36_very_dark_gray_8
texture { surface {
  color white
  ambient 0
  diffuse 0.196078
  } }

define ICP36_light_gray_9
texture { surface {
  color white
  diffuse 0.588235
  reflection 1  // Or is Ks specular?
  } }

define LONE_SURFACE
texture { surface {
  color white
  ambient 0
  diffuse 0.941176
  } }

define default
texture { surface {
  color white
  ambient 0
  diffuse 0.941176
  } }

define LONE_SURFACE
texture { surface {
  color white
  ambient 0
  diffuse 0.941176
  } }