polyray bicorn.pi   -o bicorn.tga
polyray bifolia.pi  -o bifolia.tga
polyray boys.pi     -o boys.tga
polyray cassini.pi  -o cassini.tga
polyray csaddle.pi  -o csaddle.tga
polyray cubitube.pi -o cubitube.tga
polyray cushion.pi  -o cushion.tga
polyray devil.pi    -o devil.tga
polyray folium.pi   -o folium.tga
polyray gumdrop.pi  -o gumdrop.tga
polyray helix.pi    -o helix.tga
polyray hunt.pi     -o hunt.tga
polyray hyptorus.pi -o hyptorus.tga
polyray kampyle.pi  -o kampyle.tga
polyray kummer1.pi  -o kummer1.tga
polyray kummer2.pi  -o kummer2.tga
polyray lemnisca.pi -o lemnisca.tga
polyray loop.pi     -o loop.tga
polyray mitre.pi    -o mitre.tga
polyray monkey.pi   -o monkey.tga
polyray parabol.pi  -o parabol.tga
polyray partorus.pi -o partorus.tga
polyray piriform.pi -o piriform.tga
polyray qparab.pi   -o qparab.tga
polyray qsaddle.pi  -o qsaddle.tga
polyray quarcyl.pi  -o quarcyl.tga
polyray quarpara.pi -o quarpara.tga
polyray steiner.pi  -o steiner.tga
polyray strophid.pi -o strophid.tga
polyray tcubic.pi   -o tcubic.tga
polyray tear5.pi    -o tear5.tga
polyray tooth.pi    -o tooth.tga
polyray torus.pi    -o torus.tga
polyray trough.pi   -o trough.tga
polyray twincone.pi -o twincone.tga
polyray twinglob.pi -o twinglob.tga
polyray witch.pi    -o witch.tga
