polyray superq1.pi  -o superq1.tga
polyray superq2.pi  -o superq2.tga
polyray superq3.pi  -o superq3.tga
polyray superq4.pi  -o superq4.tga
polyray superq5.pi  -o superq5.tga
polyray superq6.pi  -o superq6.tga
polyray superq7.pi  -o superq7.tga
polyray superq8.pi  -o superq8.tga
polyray superq9.pi  -o superq9.tga
