rm blobs/*.tga
rm colormap/*.tga
rm csg/*.tga
rm flare/*.tga
rm flare/*.gif
rm function/*.tga
rm gridded/chkgrid.tga
rm gridded/cubgrid.tga
rm gridded/grid.tga
rm gridded/lensgrid.tga
rm gridded/river.tga
rm height/*.tga
rm height/*.gif
rm height/*.obj
rm height/*.exe
rm lights/*.tga
rm misc/*.tga
rm person/*.tga
rm poly/*.tga
rm raw/*.tga
rm ripple/*.tga
rm simple/*.tga
rm stones/*.tga
rm superq/*.tga
rm sweep/*.tga
rm texture/*.tga
rm uvmaps/*.tga
cd animate
rm bezier/*.gif
rm cannon/*.gif
rm displace/*.gif
rm environ/*.gif
rm flying/*.gif
rm force/*.gif
rm particle/*.gif
rm plane/*.gif
rm robarm/*.gif
rm screw/*.gif
rm spline/*.gif
rm street/*.gif
rm texanim/*.gif
rm thresh/*.gif
rm ufo/*.gif
rm whirl/*.gif
cd ..
