define trn001
transform {
   rotate <0, 20, 0>
   translate <0, 8, 6>
   scale <0.25, 0.25, 0.25>
   }

define txt001 diffusion_obj_texture

object { sphere <0, -7, -7>, 0.2 txt001 trn001 }
object { cylinder <0, -7, -7>, <0, -6, -6>, 0.2 txt001 trn001 }
object { sphere <0, -6, -6>, 0.2 txt001 trn001 }
object { cylinder <0, -6, -6>, <-1, -5, -6>, 0.2 txt001 trn001 }
object { sphere <-1, -5, -6>, 0.2 txt001 trn001 }
object { cylinder <-1, -5, -6>, <0, -5, -5>, 0.2 txt001 trn001 }
object { sphere <0, -5, -6>, 0.2 txt001 trn001 }
object { cylinder <0, -5, -6>, <-1, -5, -4>, 0.2 txt001 trn001 }
object { sphere <0, -4, -6>, 0.2 txt001 trn001 }
object { cylinder <0, -4, -6>, <1, -5, -4>, 0.2 txt001 trn001 }
object { sphere <0, -5, -5>, 0.2 txt001 trn001 }
object { cylinder <0, -5, -5>, <1, -4, -2>, 0.2 txt001 trn001 }
object { sphere <2, -5, -5>, 0.2 txt001 trn001 }
object { cylinder <2, -5, -5>, <1, -4, -3>, 0.2 txt001 trn001 }
object { sphere <-3, -4, -5>, 0.2 txt001 trn001 }
object { cylinder <-3, -4, -5>, <-3, -4, -3>, 0.2 txt001 trn001 }
object { sphere <0, -3, -5>, 0.2 txt001 trn001 }
object { cylinder <0, -3, -5>, <0, -4, -2>, 0.2 txt001 trn001 }
object { sphere <2, -3, -5>, 0.2 txt001 trn001 }
object { cylinder <2, -3, -5>, <3, -4, -3>, 0.2 txt001 trn001 }
object { sphere <0, -6, -4>, 0.2 txt001 trn001 }
object { cylinder <0, -6, -4>, <-1, -5, -6>, 0.2 txt001 trn001 }
object { sphere <-2, -5, -4>, 0.2 txt001 trn001 }
object { cylinder <-2, -5, -4>, <-1, -4, -4>, 0.2 txt001 trn001 }
object { sphere <-1, -5, -4>, 0.2 txt001 trn001 }
object { cylinder <-1, -5, -4>, <-1, -4, -2>, 0.2 txt001 trn001 }
object { sphere <0, -5, -4>, 0.2 txt001 trn001 }
object { cylinder <0, -5, -4>, <0, -4, -3>, 0.2 txt001 trn001 }
object { sphere <1, -5, -4>, 0.2 txt001 trn001 }
object { cylinder <1, -5, -4>, <2, -4, -4>, 0.2 txt001 trn001 }
object { sphere <-4, -4, -4>, 0.2 txt001 trn001 }
object { cylinder <-4, -4, -4>, <-3, -3, -4>, 0.2 txt001 trn001 }
object { sphere <-2, -4, -4>, 0.2 txt001 trn001 }
object { cylinder <-2, -4, -4>, <-2, -3, -2>, 0.2 txt001 trn001 }
object { sphere <-1, -4, -4>, 0.2 txt001 trn001 }
object { cylinder <-1, -4, -4>, <-2, -3, -2>, 0.2 txt001 trn001 }
object { sphere <0, -4, -4>, 0.2 txt001 trn001 }
object { cylinder <0, -4, -4>, <0, -3, -3>, 0.2 txt001 trn001 }
object { sphere <1, -4, -4>, 0.2 txt001 trn001 }
object { cylinder <1, -4, -4>, <1, -3, -3>, 0.2 txt001 trn001 }
object { sphere <2, -4, -4>, 0.2 txt001 trn001 }
object { cylinder <2, -4, -4>, <2, -3, -1>, 0.2 txt001 trn001 }
object { sphere <3, -4, -4>, 0.2 txt001 trn001 }
object { cylinder <3, -4, -4>, <2, -3, -1>, 0.2 txt001 trn001 }
object { sphere <4, -4, -4>, 0.2 txt001 trn001 }
object { cylinder <4, -4, -4>, <3, -3, -1>, 0.2 txt001 trn001 }
object { sphere <-4, -3, -4>, 0.2 txt001 trn001 }
object { cylinder <-4, -3, -4>, <-3, -3, -4>, 0.2 txt001 trn001 }
object { sphere <-3, -3, -4>, 0.2 txt001 trn001 }
object { cylinder <-3, -3, -4>, <-4, -3, -2>, 0.2 txt001 trn001 }
object { sphere <-2, -3, -4>, 0.2 txt001 trn001 }
object { cylinder <-2, -3, -4>, <-2, -3, -3>, 0.2 txt001 trn001 }
object { sphere <-1, -3, -4>, 0.2 txt001 trn001 }
object { cylinder <-1, -3, -4>, <-1, -3, -3>, 0.2 txt001 trn001 }
object { sphere <0, -3, -4>, 0.2 txt001 trn001 }
object { cylinder <0, -3, -4>, <1, -3, -3>, 0.2 txt001 trn001 }
object { sphere <1, -3, -4>, 0.2 txt001 trn001 }
object { cylinder <1, -3, -4>, <1, -3, -2>, 0.2 txt001 trn001 }
object { sphere <2, -3, -4>, 0.2 txt001 trn001 }
object { cylinder <2, -3, -4>, <1, -3, -3>, 0.2 txt001 trn001 }
object { sphere <3, -3, -4>, 0.2 txt001 trn001 }
object { cylinder <3, -3, -4>, <4, -3, -3>, 0.2 txt001 trn001 }
object { sphere <4, -3, -4>, 0.2 txt001 trn001 }
object { cylinder <4, -3, -4>, <3, -3, -2>, 0.2 txt001 trn001 }
object { sphere <5, -3, -4>, 0.2 txt001 trn001 }
object { cylinder <5, -3, -4>, <4, -3, -1>, 0.2 txt001 trn001 }
object { sphere <-3, -2, -4>, 0.2 txt001 trn001 }
object { cylinder <-3, -2, -4>, <-2, -3, -1>, 0.2 txt001 trn001 }
object { sphere <-2, -2, -4>, 0.2 txt001 trn001 }
object { cylinder <-2, -2, -4>, <-2, -3, -4>, 0.2 txt001 trn001 }
object { sphere <-1, -2, -4>, 0.2 txt001 trn001 }
object { cylinder <-1, -2, -4>, <-1, -3, -1>, 0.2 txt001 trn001 }
object { sphere <0, -2, -4>, 0.2 txt001 trn001 }
object { cylinder <0, -2, -4>, <1, -3, -1>, 0.2 txt001 trn001 }
object { sphere <1, -2, -4>, 0.2 txt001 trn001 }
object { cylinder <1, -2, -4>, <1, -3, -3>, 0.2 txt001 trn001 }
object { sphere <2, -2, -4>, 0.2 txt001 trn001 }
object { cylinder <2, -2, -4>, <1, -3, -1>, 0.2 txt001 trn001 }
object { sphere <3, -2, -4>, 0.2 txt001 trn001 }
object { cylinder <3, -2, -4>, <3, -3, -3>, 0.2 txt001 trn001 }
object { sphere <-5, -4, -3>, 0.2 txt001 trn001 }
object { cylinder <-5, -4, -3>, <-4, -3, -3>, 0.2 txt001 trn001 }
object { sphere <-3, -4, -3>, 0.2 txt001 trn001 }
object { cylinder <-3, -4, -3>, <-2, -3, -3>, 0.2 txt001 trn001 }
object { sphere <-2, -4, -3>, 0.2 txt001 trn001 }
object { cylinder <-2, -4, -3>, <-1, -3, -3>, 0.2 txt001 trn001 }
object { sphere <-1, -4, -3>, 0.2 txt001 trn001 }
object { cylinder <-1, -4, -3>, <0, -3, -3>, 0.2 txt001 trn001 }
object { sphere <0, -4, -3>, 0.2 txt001 trn001 }
object { cylinder <0, -4, -3>, <0, -3, -2>, 0.2 txt001 trn001 }
object { sphere <1, -4, -3>, 0.2 txt001 trn001 }
object { cylinder <1, -4, -3>, <2, -3, -3>, 0.2 txt001 trn001 }
object { sphere <2, -4, -3>, 0.2 txt001 trn001 }
object { cylinder <2, -4, -3>, <2, -3, -1>, 0.2 txt001 trn001 }
object { sphere <3, -4, -3>, 0.2 txt001 trn001 }
object { cylinder <3, -4, -3>, <2, -4, -2>, 0.2 txt001 trn001 }
object { sphere <-5, -3, -3>, 0.2 txt001 trn001 }
object { cylinder <-5, -3, -3>, <-4, -2, -3>, 0.2 txt001 trn001 }
object { sphere <-4, -3, -3>, 0.2 txt001 trn001 }
object { cylinder <-4, -3, -3>, <-3, -2, -1>, 0.2 txt001 trn001 }
object { sphere <-3, -3, -3>, 0.2 txt001 trn001 }
object { cylinder <-3, -3, -3>, <-2, -2, -1>, 0.2 txt001 trn001 }
object { sphere <-2, -3, -3>, 0.2 txt001 trn001 }
object { cylinder <-2, -3, -3>, <-2, -2, -2>, 0.2 txt001 trn001 }
object { sphere <-1, -3, -3>, 0.2 txt001 trn001 }
object { cylinder <-1, -3, -3>, <0, -3, -2>, 0.2 txt001 trn001 }
object { sphere <0, -3, -3>, 0.2 txt001 trn001 }
object { cylinder <0, -3, -3>, <0, -2, 0>, 0.2 txt001 trn001 }
object { sphere <1, -3, -3>, 0.2 txt001 trn001 }
object { cylinder <1, -3, -3>, <0, -2, -1>, 0.2 txt001 trn001 }
object { sphere <2, -3, -3>, 0.2 txt001 trn001 }
object { cylinder <2, -3, -3>, <2, -2, -1>, 0.2 txt001 trn001 }
object { sphere <3, -3, -3>, 0.2 txt001 trn001 }
object { cylinder <3, -3, -3>, <3, -2, -1>, 0.2 txt001 trn001 }
object { sphere <4, -3, -3>, 0.2 txt001 trn001 }
object { cylinder <4, -3, -3>, <3, -2, 0>, 0.2 txt001 trn001 }
object { sphere <5, -3, -3>, 0.2 txt001 trn001 }
object { cylinder <5, -3, -3>, <4, -3, -3>, 0.2 txt001 trn001 }
object { sphere <-4, -2, -3>, 0.2 txt001 trn001 }
object { cylinder <-4, -2, -3>, <-3, -2, -2>, 0.2 txt001 trn001 }
object { sphere <-3, -2, -3>, 0.2 txt001 trn001 }
object { cylinder <-3, -2, -3>, <-2, -2, -2>, 0.2 txt001 trn001 }
object { sphere <-2, -2, -3>, 0.2 txt001 trn001 }
object { cylinder <-2, -2, -3>, <-3, -2, -3>, 0.2 txt001 trn001 }
object { sphere <-1, -2, -3>, 0.2 txt001 trn001 }
object { cylinder <-1, -2, -3>, <-2, -2, -1>, 0.2 txt001 trn001 }
object { sphere <0, -2, -3>, 0.2 txt001 trn001 }
object { cylinder <0, -2, -3>, <1, -2, -2>, 0.2 txt001 trn001 }
object { sphere <1, -2, -3>, 0.2 txt001 trn001 }
object { cylinder <1, -2, -3>, <1, -3, -1>, 0.2 txt001 trn001 }
object { sphere <2, -2, -3>, 0.2 txt001 trn001 }
object { cylinder <2, -2, -3>, <2, -2, -1>, 0.2 txt001 trn001 }
object { sphere <3, -2, -3>, 0.2 txt001 trn001 }
object { cylinder <3, -2, -3>, <2, -2, 0>, 0.2 txt001 trn001 }
object { sphere <4, -2, -3>, 0.2 txt001 trn001 }
object { cylinder <4, -2, -3>, <4, -2, 0>, 0.2 txt001 trn001 }
object { sphere <-4, -1, -3>, 0.2 txt001 trn001 }
object { cylinder <-4, -1, -3>, <-3, -2, -3>, 0.2 txt001 trn001 }
object { sphere <-3, -1, -3>, 0.2 txt001 trn001 }
object { cylinder <-3, -1, -3>, <-3, -2, -2>, 0.2 txt001 trn001 }
object { sphere <-2, -1, -3>, 0.2 txt001 trn001 }
object { cylinder <-2, -1, -3>, <-3, -2, -3>, 0.2 txt001 trn001 }
object { sphere <-1, -1, -3>, 0.2 txt001 trn001 }
object { cylinder <-1, -1, -3>, <-1, -2, 0>, 0.2 txt001 trn001 }
object { sphere <0, -1, -3>, 0.2 txt001 trn001 }
object { cylinder <0, -1, -3>, <0, -2, -2>, 0.2 txt001 trn001 }
object { sphere <1, -1, -3>, 0.2 txt001 trn001 }
object { cylinder <1, -1, -3>, <0, -2, -3>, 0.2 txt001 trn001 }
object { sphere <2, -1, -3>, 0.2 txt001 trn001 }
object { cylinder <2, -1, -3>, <1, -2, 0>, 0.2 txt001 trn001 }
object { sphere <3, -1, -3>, 0.2 txt001 trn001 }
object { cylinder <3, -1, -3>, <3, -2, -1>, 0.2 txt001 trn001 }
object { sphere <4, -1, -3>, 0.2 txt001 trn001 }
object { cylinder <4, -1, -3>, <4, -2, -1>, 0.2 txt001 trn001 }
object { sphere <-4, -4, -2>, 0.2 txt001 trn001 }
object { cylinder <-4, -4, -2>, <-3, -3, -2>, 0.2 txt001 trn001 }
object { sphere <-2, -4, -2>, 0.2 txt001 trn001 }
object { cylinder <-2, -4, -2>, <-1, -3, -4>, 0.2 txt001 trn001 }
object { sphere <-1, -4, -2>, 0.2 txt001 trn001 }
object { cylinder <-1, -4, -2>, <-1, -3, -2>, 0.2 txt001 trn001 }
object { sphere <0, -4, -2>, 0.2 txt001 trn001 }
object { cylinder <0, -4, -2>, <0, -3, -4>, 0.2 txt001 trn001 }
object { sphere <1, -4, -2>, 0.2 txt001 trn001 }
object { cylinder <1, -4, -2>, <1, -3, -1>, 0.2 txt001 trn001 }
object { sphere <2, -4, -2>, 0.2 txt001 trn001 }
object { cylinder <2, -4, -2>, <3, -3, -2>, 0.2 txt001 trn001 }
object { sphere <3, -4, -2>, 0.2 txt001 trn001 }
object { cylinder <3, -4, -2>, <4, -3, -2>, 0.2 txt001 trn001 }
object { sphere <-5, -3, -2>, 0.2 txt001 trn001 }
object { cylinder <-5, -3, -2>, <-4, -2, -2>, 0.2 txt001 trn001 }
object { sphere <-4, -3, -2>, 0.2 txt001 trn001 }
object { cylinder <-4, -3, -2>, <-3, -2, 0>, 0.2 txt001 trn001 }
object { sphere <-3, -3, -2>, 0.2 txt001 trn001 }
object { cylinder <-3, -3, -2>, <-2, -2, -2>, 0.2 txt001 trn001 }
object { sphere <-2, -3, -2>, 0.2 txt001 trn001 }
object { cylinder <-2, -3, -2>, <-1, -2, 0>, 0.2 txt001 trn001 }
object { sphere <-1, -3, -2>, 0.2 txt001 trn001 }
object { cylinder <-1, -3, -2>, <-1, -2, -1>, 0.2 txt001 trn001 }
object { sphere <0, -3, -2>, 0.2 txt001 trn001 }
object { cylinder <0, -3, -2>, <0, -2, -2>, 0.2 txt001 trn001 }
object { sphere <1, -3, -2>, 0.2 txt001 trn001 }
object { cylinder <1, -3, -2>, <1, -2, -1>, 0.2 txt001 trn001 }
object { sphere <2, -3, -2>, 0.2 txt001 trn001 }
object { cylinder <2, -3, -2>, <2, -2, -1>, 0.2 txt001 trn001 }
object { sphere <3, -3, -2>, 0.2 txt001 trn001 }
object { cylinder <3, -3, -2>, <2, -2, -2>, 0.2 txt001 trn001 }
object { sphere <4, -3, -2>, 0.2 txt001 trn001 }
object { cylinder <4, -3, -2>, <4, -2, 0>, 0.2 txt001 trn001 }
object { sphere <5, -3, -2>, 0.2 txt001 trn001 }
object { cylinder <5, -3, -2>, <4, -2, 0>, 0.2 txt001 trn001 }
object { sphere <-4, -2, -2>, 0.2 txt001 trn001 }
object { cylinder <-4, -2, -2>, <-3, -1, 0>, 0.2 txt001 trn001 }
object { sphere <-3, -2, -2>, 0.2 txt001 trn001 }
object { cylinder <-3, -2, -2>, <-2, -1, 0>, 0.2 txt001 trn001 }
object { sphere <-2, -2, -2>, 0.2 txt001 trn001 }
object { cylinder <-2, -2, -2>, <-1, -1, -2>, 0.2 txt001 trn001 }
object { sphere <-1, -2, -2>, 0.2 txt001 trn001 }
object { cylinder <-1, -2, -2>, <0, -2, -2>, 0.2 txt001 trn001 }
object { sphere <0, -2, -2>, 0.2 txt001 trn001 }
object { cylinder <0, -2, -2>, <0, -1, 0>, 0.2 txt001 trn001 }
object { sphere <1, -2, -2>, 0.2 txt001 trn001 }
object { cylinder <1, -2, -2>, <1, -1, 0>, 0.2 txt001 trn001 }
object { sphere <2, -2, -2>, 0.2 txt001 trn001 }
object { cylinder <2, -2, -2>, <1, -1, 0>, 0.2 txt001 trn001 }
object { sphere <3, -2, -2>, 0.2 txt001 trn001 }
object { cylinder <3, -2, -2>, <2, -2, -1>, 0.2 txt001 trn001 }
object { sphere <4, -2, -2>, 0.2 txt001 trn001 }
object { cylinder <4, -2, -2>, <4, -1, 1>, 0.2 txt001 trn001 }
object { sphere <5, -2, -2>, 0.2 txt001 trn001 }
object { cylinder <5, -2, -2>, <4, -1, 1>, 0.2 txt001 trn001 }
object { sphere <6, -2, -2>, 0.2 txt001 trn001 }
object { cylinder <6, -2, -2>, <6, -1, -1>, 0.2 txt001 trn001 }
object { sphere <-4, -1, -2>, 0.2 txt001 trn001 }
object { cylinder <-4, -1, -2>, <-3, -2, 0>, 0.2 txt001 trn001 }
object { sphere <-3, -1, -2>, 0.2 txt001 trn001 }
object { cylinder <-3, -1, -2>, <-2, -1, 1>, 0.2 txt001 trn001 }
object { sphere <-2, -1, -2>, 0.2 txt001 trn001 }
object { cylinder <-2, -1, -2>, <-2, -1, 0>, 0.2 txt001 trn001 }
object { sphere <-1, -1, -2>, 0.2 txt001 trn001 }
object { cylinder <-1, -1, -2>, <0, -2, -2>, 0.2 txt001 trn001 }
object { sphere <0, -1, -2>, 0.2 txt001 trn001 }
object { cylinder <0, -1, -2>, <-1, -1, -1>, 0.2 txt001 trn001 }
object { sphere <1, -1, -2>, 0.2 txt001 trn001 }
object { cylinder <1, -1, -2>, <0, -1, -1>, 0.2 txt001 trn001 }
object { sphere <2, -1, -2>, 0.2 txt001 trn001 }
object { cylinder <2, -1, -2>, <1, -1, -1>, 0.2 txt001 trn001 }
object { sphere <3, -1, -2>, 0.2 txt001 trn001 }
object { cylinder <3, -1, -2>, <2, -2, -2>, 0.2 txt001 trn001 }
object { sphere <4, -1, -2>, 0.2 txt001 trn001 }
object { cylinder <4, -1, -2>, <3, -1, -1>, 0.2 txt001 trn001 }
object { sphere <7, -1, -2>, 0.2 txt001 trn001 }
object { cylinder <7, -1, -2>, <6, -1, 1>, 0.2 txt001 trn001 }
object { sphere <-3, 0, -2>, 0.2 txt001 trn001 }
object { cylinder <-3, 0, -2>, <-3, -1, 1>, 0.2 txt001 trn001 }
object { sphere <-2, 0, -2>, 0.2 txt001 trn001 }
object { cylinder <-2, 0, -2>, <-2, -1, -1>, 0.2 txt001 trn001 }
object { sphere <-1, 0, -2>, 0.2 txt001 trn001 }
object { cylinder <-1, 0, -2>, <-1, -1, -1>, 0.2 txt001 trn001 }
object { sphere <0, 0, -2>, 0.2 txt001 trn001 }
object { cylinder <0, 0, -2>, <0, -1, 0>, 0.2 txt001 trn001 }
object { sphere <1, 0, -2>, 0.2 txt001 trn001 }
object { cylinder <1, 0, -2>, <1, -1, -2>, 0.2 txt001 trn001 }
object { sphere <2, 0, -2>, 0.2 txt001 trn001 }
object { cylinder <2, 0, -2>, <1, -1, 1>, 0.2 txt001 trn001 }
object { sphere <3, 0, -2>, 0.2 txt001 trn001 }
object { cylinder <3, 0, -2>, <2, -1, -2>, 0.2 txt001 trn001 }
object { sphere <4, 0, -2>, 0.2 txt001 trn001 }
object { cylinder <4, 0, -2>, <3, -1, -2>, 0.2 txt001 trn001 }
object { sphere <-4, -3, -1>, 0.2 txt001 trn001 }
object { cylinder <-4, -3, -1>, <-3, -2, -3>, 0.2 txt001 trn001 }
object { sphere <-3, -3, -1>, 0.2 txt001 trn001 }
object { cylinder <-3, -3, -1>, <-3, -2, 0>, 0.2 txt001 trn001 }
object { sphere <-2, -3, -1>, 0.2 txt001 trn001 }
object { cylinder <-2, -3, -1>, <-1, -2, -3>, 0.2 txt001 trn001 }
object { sphere <-1, -3, -1>, 0.2 txt001 trn001 }
object { cylinder <-1, -3, -1>, <-1, -2, -1>, 0.2 txt001 trn001 }
object { sphere <0, -3, -1>, 0.2 txt001 trn001 }
object { cylinder <0, -3, -1>, <0, -2, -4>, 0.2 txt001 trn001 }
object { sphere <1, -3, -1>, 0.2 txt001 trn001 }
object { cylinder <1, -3, -1>, <0, -2, -1>, 0.2 txt001 trn001 }
object { sphere <2, -3, -1>, 0.2 txt001 trn001 }
object { cylinder <2, -3, -1>, <3, -2, -1>, 0.2 txt001 trn001 }
object { sphere <3, -3, -1>, 0.2 txt001 trn001 }
object { cylinder <3, -3, -1>, <3, -2, 0>, 0.2 txt001 trn001 }
object { sphere <4, -3, -1>, 0.2 txt001 trn001 }
object { cylinder <4, -3, -1>, <3, -2, -1>, 0.2 txt001 trn001 }
object { sphere <-5, -2, -1>, 0.2 txt001 trn001 }
object { cylinder <-5, -2, -1>, <-4, -1, 1>, 0.2 txt001 trn001 }
object { sphere <-4, -2, -1>, 0.2 txt001 trn001 }
object { cylinder <-4, -2, -1>, <-3, -2, -3>, 0.2 txt001 trn001 }
object { sphere <-3, -2, -1>, 0.2 txt001 trn001 }
object { cylinder <-3, -2, -1>, <-2, -1, -3>, 0.2 txt001 trn001 }
object { sphere <-2, -2, -1>, 0.2 txt001 trn001 }
object { cylinder <-2, -2, -1>, <-2, -1, -1>, 0.2 txt001 trn001 }
object { sphere <-1, -2, -1>, 0.2 txt001 trn001 }
object { cylinder <-1, -2, -1>, <0, -1, -1>, 0.2 txt001 trn001 }
object { sphere <0, -2, -1>, 0.2 txt001 trn001 }
object { cylinder <0, -2, -1>, <1, -1, -1>, 0.2 txt001 trn001 }
object { sphere <1, -2, -1>, 0.2 txt001 trn001 }
object { cylinder <1, -2, -1>, <1, -1, -2>, 0.2 txt001 trn001 }
object { sphere <2, -2, -1>, 0.2 txt001 trn001 }
object { cylinder <2, -2, -1>, <1, -1, -1>, 0.2 txt001 trn001 }
object { sphere <3, -2, -1>, 0.2 txt001 trn001 }
object { cylinder <3, -2, -1>, <2, -1, 1>, 0.2 txt001 trn001 }
object { sphere <4, -2, -1>, 0.2 txt001 trn001 }
object { cylinder <4, -2, -1>, <3, -1, -1>, 0.2 txt001 trn001 }
object { sphere <7, -2, -1>, 0.2 txt001 trn001 }
object { cylinder <7, -2, -1>, <6, -1, -1>, 0.2 txt001 trn001 }
object { sphere <-4, -1, -1>, 0.2 txt001 trn001 }
object { cylinder <-4, -1, -1>, <-3, -1, -1>, 0.2 txt001 trn001 }
object { sphere <-3, -1, -1>, 0.2 txt001 trn001 }
object { cylinder <-3, -1, -1>, <-2, 0, -1>, 0.2 txt001 trn001 }
object { sphere <-2, -1, -1>, 0.2 txt001 trn001 }
object { cylinder <-2, -1, -1>, <-1, 0, 1>, 0.2 txt001 trn001 }
object { sphere <-1, -1, -1>, 0.2 txt001 trn001 }
object { cylinder <-1, -1, -1>, <0, 0, 2>, 0.2 txt001 trn001 }
object { sphere <0, -1, -1>, 0.2 txt001 trn001 }
object { cylinder <0, -1, -1>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <1, -1, -1>, 0.2 txt001 trn001 }
object { cylinder <1, -1, -1>, <1, 0, 0>, 0.2 txt001 trn001 }
object { sphere <2, -1, -1>, 0.2 txt001 trn001 }
object { cylinder <2, -1, -1>, <1, 0, -1>, 0.2 txt001 trn001 }
object { sphere <3, -1, -1>, 0.2 txt001 trn001 }
object { cylinder <3, -1, -1>, <3, 0, 0>, 0.2 txt001 trn001 }
object { sphere <4, -1, -1>, 0.2 txt001 trn001 }
object { cylinder <4, -1, -1>, <3, 0, 2>, 0.2 txt001 trn001 }
object { sphere <5, -1, -1>, 0.2 txt001 trn001 }
object { cylinder <5, -1, -1>, <4, -2, -1>, 0.2 txt001 trn001 }
object { sphere <6, -1, -1>, 0.2 txt001 trn001 }
object { cylinder <6, -1, -1>, <6, 0, 2>, 0.2 txt001 trn001 }
object { sphere <-5, 0, -1>, 0.2 txt001 trn001 }
object { cylinder <-5, 0, -1>, <-4, -1, -3>, 0.2 txt001 trn001 }
object { sphere <-4, 0, -1>, 0.2 txt001 trn001 }
object { cylinder <-4, 0, -1>, <-3, 0, -1>, 0.2 txt001 trn001 }
object { sphere <-3, 0, -1>, 0.2 txt001 trn001 }
object { cylinder <-3, 0, -1>, <-2, 0, -1>, 0.2 txt001 trn001 }
object { sphere <-2, 0, -1>, 0.2 txt001 trn001 }
object { sphere <-1, 0, -1>, 0.2 txt001 trn001 }
object { cylinder <-1, 0, -1>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <0, 0, -1>, 0.2 txt001 trn001 }
object { cylinder <0, 0, -1>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <1, 0, -1>, 0.2 txt001 trn001 }
object { cylinder <1, 0, -1>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <2, 0, -1>, 0.2 txt001 trn001 }
object { cylinder <2, 0, -1>, <1, 0, 0>, 0.2 txt001 trn001 }
object { sphere <3, 0, -1>, 0.2 txt001 trn001 }
object { cylinder <3, 0, -1>, <2, 0, 1>, 0.2 txt001 trn001 }
object { sphere <4, 0, -1>, 0.2 txt001 trn001 }
object { cylinder <4, 0, -1>, <3, -1, -1>, 0.2 txt001 trn001 }
object { sphere <5, 0, -1>, 0.2 txt001 trn001 }
object { cylinder <5, 0, -1>, <4, 0, 0>, 0.2 txt001 trn001 }
object { sphere <6, 0, -1>, 0.2 txt001 trn001 }
object { cylinder <6, 0, -1>, <5, 0, -1>, 0.2 txt001 trn001 }
object { sphere <-4, 1, -1>, 0.2 txt001 trn001 }
object { cylinder <-4, 1, -1>, <-4, 0, 1>, 0.2 txt001 trn001 }
object { sphere <-3, 1, -1>, 0.2 txt001 trn001 }
object { cylinder <-3, 1, -1>, <-2, 0, -1>, 0.2 txt001 trn001 }
object { sphere <-2, 1, -1>, 0.2 txt001 trn001 }
object { cylinder <-2, 1, -1>, <-1, 0, -1>, 0.2 txt001 trn001 }
object { sphere <-1, 1, -1>, 0.2 txt001 trn001 }
object { cylinder <-1, 1, -1>, <0, 0, 2>, 0.2 txt001 trn001 }
object { sphere <0, 1, -1>, 0.2 txt001 trn001 }
object { cylinder <0, 1, -1>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <1, 1, -1>, 0.2 txt001 trn001 }
object { cylinder <1, 1, -1>, <0, 0, 2>, 0.2 txt001 trn001 }
object { sphere <2, 1, -1>, 0.2 txt001 trn001 }
object { cylinder <2, 1, -1>, <1, 0, 2>, 0.2 txt001 trn001 }
object { sphere <3, 1, -1>, 0.2 txt001 trn001 }
object { cylinder <3, 1, -1>, <3, 0, 0>, 0.2 txt001 trn001 }
object { sphere <4, 1, -1>, 0.2 txt001 trn001 }
object { cylinder <4, 1, -1>, <3, 0, 1>, 0.2 txt001 trn001 }
object { sphere <5, 1, -1>, 0.2 txt001 trn001 }
object { cylinder <5, 1, -1>, <4, 0, 1>, 0.2 txt001 trn001 }
object { sphere <-4, -2, 0>, 0.2 txt001 trn001 }
object { cylinder <-4, -2, 0>, <-3, -1, 0>, 0.2 txt001 trn001 }
object { sphere <-3, -2, 0>, 0.2 txt001 trn001 }
object { cylinder <-3, -2, 0>, <-2, -1, -2>, 0.2 txt001 trn001 }
object { sphere <-2, -2, 0>, 0.2 txt001 trn001 }
object { cylinder <-2, -2, 0>, <-1, -1, -2>, 0.2 txt001 trn001 }
object { sphere <-1, -2, 0>, 0.2 txt001 trn001 }
object { cylinder <-1, -2, 0>, <0, -1, 0>, 0.2 txt001 trn001 }
object { sphere <0, -2, 0>, 0.2 txt001 trn001 }
object { cylinder <0, -2, 0>, <0, -1, 1>, 0.2 txt001 trn001 }
object { sphere <1, -2, 0>, 0.2 txt001 trn001 }
object { cylinder <1, -2, 0>, <2, -1, 0>, 0.2 txt001 trn001 }
object { sphere <2, -2, 0>, 0.2 txt001 trn001 }
object { cylinder <2, -2, 0>, <1, -1, -2>, 0.2 txt001 trn001 }
object { sphere <3, -2, 0>, 0.2 txt001 trn001 }
object { cylinder <3, -2, 0>, <3, -1, -1>, 0.2 txt001 trn001 }
object { sphere <4, -2, 0>, 0.2 txt001 trn001 }
object { cylinder <4, -2, 0>, <3, -1, -3>, 0.2 txt001 trn001 }
object { sphere <5, -2, 0>, 0.2 txt001 trn001 }
object { cylinder <5, -2, 0>, <4, -1, -2>, 0.2 txt001 trn001 }
object { sphere <-4, -1, 0>, 0.2 txt001 trn001 }
object { cylinder <-4, -1, 0>, <-4, -1, -3>, 0.2 txt001 trn001 }
object { sphere <-3, -1, 0>, 0.2 txt001 trn001 }
object { cylinder <-3, -1, 0>, <-2, -1, 1>, 0.2 txt001 trn001 }
object { sphere <-2, -1, 0>, 0.2 txt001 trn001 }
object { cylinder <-2, -1, 0>, <-1, 0, 2>, 0.2 txt001 trn001 }
object { sphere <-1, -1, 0>, 0.2 txt001 trn001 }
object { cylinder <-1, -1, 0>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <0, -1, 0>, 0.2 txt001 trn001 }
object { cylinder <0, -1, 0>, <0, 0, 2>, 0.2 txt001 trn001 }
object { sphere <1, -1, 0>, 0.2 txt001 trn001 }
object { cylinder <1, -1, 0>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <2, -1, 0>, 0.2 txt001 trn001 }
object { cylinder <2, -1, 0>, <2, 0, 0>, 0.2 txt001 trn001 }
object { sphere <3, -1, 0>, 0.2 txt001 trn001 }
object { cylinder <3, -1, 0>, <2, 0, 2>, 0.2 txt001 trn001 }
object { sphere <4, -1, 0>, 0.2 txt001 trn001 }
object { cylinder <4, -1, 0>, <3, 0, 0>, 0.2 txt001 trn001 }
object { sphere <5, -1, 0>, 0.2 txt001 trn001 }
object { cylinder <5, -1, 0>, <5, 0, 2>, 0.2 txt001 trn001 }
object { sphere <6, -1, 0>, 0.2 txt001 trn001 }
object { cylinder <6, -1, 0>, <5, 0, 2>, 0.2 txt001 trn001 }
object { sphere <-5, 0, 0>, 0.2 txt001 trn001 }
object { cylinder <-5, 0, 0>, <-4, -1, -2>, 0.2 txt001 trn001 }
object { sphere <-3, 0, 0>, 0.2 txt001 trn001 }
object { cylinder <-3, 0, 0>, <-2, 1, 0>, 0.2 txt001 trn001 }
object { sphere <-2, 0, 0>, 0.2 txt001 trn001 }
object { cylinder <-2, 0, 0>, <-2, -1, 0>, 0.2 txt001 trn001 }
object { sphere <-1, 0, 0>, 0.2 txt001 trn001 }
object { cylinder <-1, 0, 0>, <-1, -1, 0>, 0.2 txt001 trn001 }
object { sphere <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <1, 0, 0>, 0.2 txt001 trn001 }
object { cylinder <1, 0, 0>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <2, 0, 0>, 0.2 txt001 trn001 }
object { cylinder <2, 0, 0>, <2, 1, 2>, 0.2 txt001 trn001 }
object { sphere <3, 0, 0>, 0.2 txt001 trn001 }
object { cylinder <3, 0, 0>, <3, 1, 3>, 0.2 txt001 trn001 }
object { sphere <4, 0, 0>, 0.2 txt001 trn001 }
object { cylinder <4, 0, 0>, <4, 1, 1>, 0.2 txt001 trn001 }
object { sphere <5, 0, 0>, 0.2 txt001 trn001 }
object { cylinder <5, 0, 0>, <5, 1, 0>, 0.2 txt001 trn001 }
object { sphere <6, 0, 0>, 0.2 txt001 trn001 }
object { cylinder <6, 0, 0>, <5, 1, 0>, 0.2 txt001 trn001 }
object { sphere <-4, 1, 0>, 0.2 txt001 trn001 }
object { cylinder <-4, 1, 0>, <-3, 1, 1>, 0.2 txt001 trn001 }
object { sphere <-3, 1, 0>, 0.2 txt001 trn001 }
object { cylinder <-3, 1, 0>, <-2, 0, -2>, 0.2 txt001 trn001 }
object { sphere <-2, 1, 0>, 0.2 txt001 trn001 }
object { cylinder <-2, 1, 0>, <-1, 1, -1>, 0.2 txt001 trn001 }
object { sphere <-1, 1, 0>, 0.2 txt001 trn001 }
object { sphere <0, 1, 0>, 0.2 txt001 trn001 }
object { cylinder <0, 1, 0>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <1, 1, 0>, 0.2 txt001 trn001 }
object { cylinder <1, 1, 0>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <2, 1, 0>, 0.2 txt001 trn001 }
object { cylinder <2, 1, 0>, <1, 1, 2>, 0.2 txt001 trn001 }
object { sphere <3, 1, 0>, 0.2 txt001 trn001 }
object { cylinder <3, 1, 0>, <2, 1, 3>, 0.2 txt001 trn001 }
object { sphere <4, 1, 0>, 0.2 txt001 trn001 }
object { cylinder <4, 1, 0>, <3, 1, -1>, 0.2 txt001 trn001 }
object { sphere <5, 1, 0>, 0.2 txt001 trn001 }
object { cylinder <5, 1, 0>, <4, 1, 0>, 0.2 txt001 trn001 }
object { sphere <6, 1, 0>, 0.2 txt001 trn001 }
object { cylinder <6, 1, 0>, <5, 1, 2>, 0.2 txt001 trn001 }
object { sphere <-4, 2, 0>, 0.2 txt001 trn001 }
object { cylinder <-4, 2, 0>, <-4, 1, 3>, 0.2 txt001 trn001 }
object { sphere <-2, 2, 0>, 0.2 txt001 trn001 }
object { cylinder <-2, 2, 0>, <-2, 1, 3>, 0.2 txt001 trn001 }
object { sphere <-1, 2, 0>, 0.2 txt001 trn001 }
object { cylinder <-1, 2, 0>, <0, 1, 0>, 0.2 txt001 trn001 }
object { sphere <0, 2, 0>, 0.2 txt001 trn001 }
object { cylinder <0, 2, 0>, <-1, 1, 2>, 0.2 txt001 trn001 }
object { sphere <1, 2, 0>, 0.2 txt001 trn001 }
object { cylinder <1, 2, 0>, <1, 1, 3>, 0.2 txt001 trn001 }
object { sphere <2, 2, 0>, 0.2 txt001 trn001 }
object { cylinder <2, 2, 0>, <3, 1, 3>, 0.2 txt001 trn001 }
object { sphere <3, 2, 0>, 0.2 txt001 trn001 }
object { cylinder <3, 2, 0>, <3, 1, 1>, 0.2 txt001 trn001 }
object { sphere <4, 2, 0>, 0.2 txt001 trn001 }
object { cylinder <4, 2, 0>, <4, 1, 2>, 0.2 txt001 trn001 }
object { sphere <5, 2, 0>, 0.2 txt001 trn001 }
object { cylinder <5, 2, 0>, <5, 1, -1>, 0.2 txt001 trn001 }
object { sphere <-4, -1, 1>, 0.2 txt001 trn001 }
object { cylinder <-4, -1, 1>, <-3, 0, 1>, 0.2 txt001 trn001 }
object { sphere <-3, -1, 1>, 0.2 txt001 trn001 }
object { cylinder <-3, -1, 1>, <-2, 0, 1>, 0.2 txt001 trn001 }
object { sphere <-2, -1, 1>, 0.2 txt001 trn001 }
object { cylinder <-2, -1, 1>, <-1, 0, -1>, 0.2 txt001 trn001 }
object { sphere <-1, -1, 1>, 0.2 txt001 trn001 }
object { cylinder <-1, -1, 1>, <0, 0, -1>, 0.2 txt001 trn001 }
object { sphere <0, -1, 1>, 0.2 txt001 trn001 }
object { cylinder <0, -1, 1>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <1, -1, 1>, 0.2 txt001 trn001 }
object { cylinder <1, -1, 1>, <0, 0, 1>, 0.2 txt001 trn001 }
object { sphere <2, -1, 1>, 0.2 txt001 trn001 }
object { cylinder <2, -1, 1>, <3, 0, 1>, 0.2 txt001 trn001 }
object { sphere <3, -1, 1>, 0.2 txt001 trn001 }
object { cylinder <3, -1, 1>, <4, 0, -1>, 0.2 txt001 trn001 }
object { sphere <4, -1, 1>, 0.2 txt001 trn001 }
object { cylinder <4, -1, 1>, <4, 0, 0>, 0.2 txt001 trn001 }
object { sphere <5, -1, 1>, 0.2 txt001 trn001 }
object { cylinder <5, -1, 1>, <4, 0, 1>, 0.2 txt001 trn001 }
object { sphere <6, -1, 1>, 0.2 txt001 trn001 }
object { cylinder <6, -1, 1>, <6, 0, 2>, 0.2 txt001 trn001 }
object { sphere <-4, 0, 1>, 0.2 txt001 trn001 }
object { cylinder <-4, 0, 1>, <-3, 0, 0>, 0.2 txt001 trn001 }
object { sphere <-3, 0, 1>, 0.2 txt001 trn001 }
object { cylinder <-3, 0, 1>, <-2, 1, 3>, 0.2 txt001 trn001 }
object { sphere <-2, 0, 1>, 0.2 txt001 trn001 }
object { cylinder <-2, 0, 1>, <-1, 0, 0>, 0.2 txt001 trn001 }
object { sphere <-1, 0, 1>, 0.2 txt001 trn001 }
object { cylinder <-1, 0, 1>, <0, 0, 0>, 0.2 txt001 trn001 }
object { sphere <0, 0, 1>, 0.2 txt001 trn001 }
object { cylinder <0, 0, 1>, <1, 0, -1>, 0.2 txt001 trn001 }
object { sphere <1, 0, 1>, 0.2 txt001 trn001 }
object { cylinder <1, 0, 1>, <1, 1, -1>, 0.2 txt001 trn001 }
object { sphere <2, 0, 1>, 0.2 txt001 trn001 }
object { cylinder <2, 0, 1>, <1, 1, 1>, 0.2 txt001 trn001 }
object { sphere <3, 0, 1>, 0.2 txt001 trn001 }
object { cylinder <3, 0, 1>, <2, 1, 1>, 0.2 txt001 trn001 }
object { sphere <4, 0, 1>, 0.2 txt001 trn001 }
object { cylinder <4, 0, 1>, <4, 1, 2>, 0.2 txt001 trn001 }
object { sphere <5, 0, 1>, 0.2 txt001 trn001 }
object { cylinder <5, 0, 1>, <5, 1, 0>, 0.2 txt001 trn001 }
object { sphere <-4, 1, 1>, 0.2 txt001 trn001 }
object { cylinder <-4, 1, 1>, <-3, 0, 1>, 0.2 txt001 trn001 }
object { sphere <-3, 1, 1>, 0.2 txt001 trn001 }
object { cylinder <-3, 1, 1>, <-2, 0, -2>, 0.2 txt001 trn001 }
object { sphere <-2, 1, 1>, 0.2 txt001 trn001 }
object { cylinder <-2, 1, 1>, <-1, 2, 1>, 0.2 txt001 trn001 }
object { sphere <-1, 1, 1>, 0.2 txt001 trn001 }
object { cylinder <-1, 1, 1>, <-1, 0, 1>, 0.2 txt001 trn001 }
object { sphere <0, 1, 1>, 0.2 txt001 trn001 }
object { cylinder <0, 1, 1>, <0, 0, -1>, 0.2 txt001 trn001 }
object { sphere <1, 1, 1>, 0.2 txt001 trn001 }
object { cylinder <1, 1, 1>, <0, 1, 1>, 0.2 txt001 trn001 }
object { sphere <2, 1, 1>, 0.2 txt001 trn001 }
object { cylinder <2, 1, 1>, <1, 2, 1>, 0.2 txt001 trn001 }
object { sphere <3, 1, 1>, 0.2 txt001 trn001 }
object { cylinder <3, 1, 1>, <2, 2, 1>, 0.2 txt001 trn001 }
object { sphere <4, 1, 1>, 0.2 txt001 trn001 }
object { cylinder <4, 1, 1>, <4, 0, -1>, 0.2 txt001 trn001 }
object { sphere <5, 1, 1>, 0.2 txt001 trn001 }
object { cylinder <5, 1, 1>, <4, 1, 1>, 0.2 txt001 trn001 }
object { sphere <-4, 2, 1>, 0.2 txt001 trn001 }
object { cylinder <-4, 2, 1>, <-3, 2, 4>, 0.2 txt001 trn001 }
object { sphere <-3, 2, 1>, 0.2 txt001 trn001 }
object { cylinder <-3, 2, 1>, <-2, 1, -1>, 0.2 txt001 trn001 }
object { sphere <-2, 2, 1>, 0.2 txt001 trn001 }
object { cylinder <-2, 2, 1>, <-2, 1, 1>, 0.2 txt001 trn001 }
object { sphere <-1, 2, 1>, 0.2 txt001 trn001 }
object { cylinder <-1, 2, 1>, <-1, 1, 0>, 0.2 txt001 trn001 }
object { sphere <0, 2, 1>, 0.2 txt001 trn001 }
object { cylinder <0, 2, 1>, <1, 1, -1>, 0.2 txt001 trn001 }
object { sphere <1, 2, 1>, 0.2 txt001 trn001 }
object { cylinder <1, 2, 1>, <0, 1, 1>, 0.2 txt001 trn001 }
object { sphere <2, 2, 1>, 0.2 txt001 trn001 }
object { cylinder <2, 2, 1>, <2, 2, 0>, 0.2 txt001 trn001 }
object { sphere <3, 2, 1>, 0.2 txt001 trn001 }
object { cylinder <3, 2, 1>, <2, 1, -1>, 0.2 txt001 trn001 }
object { sphere <4, 2, 1>, 0.2 txt001 trn001 }
object { cylinder <4, 2, 1>, <3, 2, 3>, 0.2 txt001 trn001 }
object { sphere <5, 2, 1>, 0.2 txt001 trn001 }
object { cylinder <5, 2, 1>, <4, 1, -1>, 0.2 txt001 trn001 }
object { sphere <6, 2, 1>, 0.2 txt001 trn001 }
object { cylinder <6, 2, 1>, <5, 2, 4>, 0.2 txt001 trn001 }
object { sphere <-3, 3, 1>, 0.2 txt001 trn001 }
object { cylinder <-3, 3, 1>, <-3, 2, 2>, 0.2 txt001 trn001 }
object { sphere <-2, 3, 1>, 0.2 txt001 trn001 }
object { cylinder <-2, 3, 1>, <-1, 2, 4>, 0.2 txt001 trn001 }
object { sphere <-1, 3, 1>, 0.2 txt001 trn001 }
object { cylinder <-1, 3, 1>, <-1, 2, 0>, 0.2 txt001 trn001 }
object { sphere <0, 3, 1>, 0.2 txt001 trn001 }
object { cylinder <0, 3, 1>, <0, 2, 1>, 0.2 txt001 trn001 }
object { sphere <1, 3, 1>, 0.2 txt001 trn001 }
object { cylinder <1, 3, 1>, <1, 2, 1>, 0.2 txt001 trn001 }
object { sphere <2, 3, 1>, 0.2 txt001 trn001 }
object { cylinder <2, 3, 1>, <1, 2, 3>, 0.2 txt001 trn001 }
object { sphere <3, 3, 1>, 0.2 txt001 trn001 }
object { cylinder <3, 3, 1>, <3, 2, 1>, 0.2 txt001 trn001 }
object { sphere <4, 3, 1>, 0.2 txt001 trn001 }
object { cylinder <4, 3, 1>, <3, 2, 1>, 0.2 txt001 trn001 }
object { sphere <6, 3, 1>, 0.2 txt001 trn001 }
object { cylinder <6, 3, 1>, <6, 2, 3>, 0.2 txt001 trn001 }
object { sphere <-2, 0, 2>, 0.2 txt001 trn001 }
object { cylinder <-2, 0, 2>, <-1, 1, -1>, 0.2 txt001 trn001 }
object { sphere <-1, 0, 2>, 0.2 txt001 trn001 }
object { cylinder <-1, 0, 2>, <0, 1, 0>, 0.2 txt001 trn001 }
object { sphere <0, 0, 2>, 0.2 txt001 trn001 }
object { cylinder <0, 0, 2>, <0, 1, 0>, 0.2 txt001 trn001 }
object { sphere <1, 0, 2>, 0.2 txt001 trn001 }
object { cylinder <1, 0, 2>, <1, 1, 3>, 0.2 txt001 trn001 }
object { sphere <2, 0, 2>, 0.2 txt001 trn001 }
object { cylinder <2, 0, 2>, <2, 1, 1>, 0.2 txt001 trn001 }
object { sphere <3, 0, 2>, 0.2 txt001 trn001 }
object { cylinder <3, 0, 2>, <2, 1, 2>, 0.2 txt001 trn001 }
object { sphere <4, 0, 2>, 0.2 txt001 trn001 }
object { cylinder <4, 0, 2>, <4, 1, -1>, 0.2 txt001 trn001 }
object { sphere <5, 0, 2>, 0.2 txt001 trn001 }
object { cylinder <5, 0, 2>, <5, 1, 2>, 0.2 txt001 trn001 }
object { sphere <6, 0, 2>, 0.2 txt001 trn001 }
object { cylinder <6, 0, 2>, <5, 1, -1>, 0.2 txt001 trn001 }
object { sphere <-3, 1, 2>, 0.2 txt001 trn001 }
object { cylinder <-3, 1, 2>, <-2, 1, -1>, 0.2 txt001 trn001 }
object { sphere <-2, 1, 2>, 0.2 txt001 trn001 }
object { cylinder <-2, 1, 2>, <-1, 2, 0>, 0.2 txt001 trn001 }
object { sphere <-1, 1, 2>, 0.2 txt001 trn001 }
object { cylinder <-1, 1, 2>, <-1, 1, 0>, 0.2 txt001 trn001 }
object { sphere <0, 1, 2>, 0.2 txt001 trn001 }
object { cylinder <0, 1, 2>, <0, 1, 1>, 0.2 txt001 trn001 }
object { sphere <1, 1, 2>, 0.2 txt001 trn001 }
object { cylinder <1, 1, 2>, <1, 2, 1>, 0.2 txt001 trn001 }
object { sphere <2, 1, 2>, 0.2 txt001 trn001 }
object { cylinder <2, 1, 2>, <1, 1, 3>, 0.2 txt001 trn001 }
object { sphere <3, 1, 2>, 0.2 txt001 trn001 }
object { cylinder <3, 1, 2>, <3, 1, -1>, 0.2 txt001 trn001 }
object { sphere <4, 1, 2>, 0.2 txt001 trn001 }
object { cylinder <4, 1, 2>, <3, 1, -1>, 0.2 txt001 trn001 }
object { sphere <5, 1, 2>, 0.2 txt001 trn001 }
object { cylinder <5, 1, 2>, <4, 2, 0>, 0.2 txt001 trn001 }
object { sphere <-3, 2, 2>, 0.2 txt001 trn001 }
object { cylinder <-3, 2, 2>, <-2, 2, 1>, 0.2 txt001 trn001 }
object { sphere <-2, 2, 2>, 0.2 txt001 trn001 }
object { cylinder <-2, 2, 2>, <-1, 2, 3>, 0.2 txt001 trn001 }
object { sphere <-1, 2, 2>, 0.2 txt001 trn001 }
object { cylinder <-1, 2, 2>, <-1, 1, 1>, 0.2 txt001 trn001 }
object { sphere <0, 2, 2>, 0.2 txt001 trn001 }
object { cylinder <0, 2, 2>, <-1, 1, 2>, 0.2 txt001 trn001 }
object { sphere <1, 2, 2>, 0.2 txt001 trn001 }
object { cylinder <1, 2, 2>, <0, 2, 0>, 0.2 txt001 trn001 }
object { sphere <2, 2, 2>, 0.2 txt001 trn001 }
object { cylinder <2, 2, 2>, <1, 1, 2>, 0.2 txt001 trn001 }
object { sphere <3, 2, 2>, 0.2 txt001 trn001 }
object { cylinder <3, 2, 2>, <2, 1, 2>, 0.2 txt001 trn001 }
object { sphere <4, 2, 2>, 0.2 txt001 trn001 }
object { cylinder <4, 2, 2>, <4, 1, 0>, 0.2 txt001 trn001 }
object { sphere <5, 2, 2>, 0.2 txt001 trn001 }
object { cylinder <5, 2, 2>, <4, 2, 2>, 0.2 txt001 trn001 }
object { sphere <-4, 3, 2>, 0.2 txt001 trn001 }
object { cylinder <-4, 3, 2>, <-4, 2, 1>, 0.2 txt001 trn001 }
object { sphere <-3, 3, 2>, 0.2 txt001 trn001 }
object { cylinder <-3, 3, 2>, <-2, 3, 1>, 0.2 txt001 trn001 }
object { sphere <-2, 3, 2>, 0.2 txt001 trn001 }
object { cylinder <-2, 3, 2>, <-1, 2, 0>, 0.2 txt001 trn001 }
object { sphere <-1, 3, 2>, 0.2 txt001 trn001 }
object { cylinder <-1, 3, 2>, <-1, 2, 1>, 0.2 txt001 trn001 }
object { sphere <0, 3, 2>, 0.2 txt001 trn001 }
object { cylinder <0, 3, 2>, <1, 3, 1>, 0.2 txt001 trn001 }
object { sphere <1, 3, 2>, 0.2 txt001 trn001 }
object { cylinder <1, 3, 2>, <1, 2, 0>, 0.2 txt001 trn001 }
object { sphere <2, 3, 2>, 0.2 txt001 trn001 }
object { cylinder <2, 3, 2>, <1, 3, 1>, 0.2 txt001 trn001 }
object { sphere <3, 3, 2>, 0.2 txt001 trn001 }
object { cylinder <3, 3, 2>, <2, 3, 2>, 0.2 txt001 trn001 }
object { sphere <4, 3, 2>, 0.2 txt001 trn001 }
object { cylinder <4, 3, 2>, <3, 2, 2>, 0.2 txt001 trn001 }
object { sphere <5, 3, 2>, 0.2 txt001 trn001 }
object { cylinder <5, 3, 2>, <4, 3, 4>, 0.2 txt001 trn001 }
object { sphere <6, 3, 2>, 0.2 txt001 trn001 }
object { cylinder <6, 3, 2>, <5, 3, 3>, 0.2 txt001 trn001 }
object { sphere <-2, 4, 2>, 0.2 txt001 trn001 }
object { cylinder <-2, 4, 2>, <-1, 3, 2>, 0.2 txt001 trn001 }
object { sphere <-1, 4, 2>, 0.2 txt001 trn001 }
object { cylinder <-1, 4, 2>, <0, 3, 2>, 0.2 txt001 trn001 }
object { sphere <0, 4, 2>, 0.2 txt001 trn001 }
object { cylinder <0, 4, 2>, <0, 3, 3>, 0.2 txt001 trn001 }
object { sphere <1, 4, 2>, 0.2 txt001 trn001 }
object { cylinder <1, 4, 2>, <0, 3, 2>, 0.2 txt001 trn001 }
object { sphere <2, 4, 2>, 0.2 txt001 trn001 }
object { cylinder <2, 4, 2>, <3, 3, 2>, 0.2 txt001 trn001 }
object { sphere <3, 4, 2>, 0.2 txt001 trn001 }
object { cylinder <3, 4, 2>, <3, 3, 1>, 0.2 txt001 trn001 }
object { sphere <4, 4, 2>, 0.2 txt001 trn001 }
object { cylinder <4, 4, 2>, <4, 3, 4>, 0.2 txt001 trn001 }
object { sphere <5, 4, 2>, 0.2 txt001 trn001 }
object { cylinder <5, 4, 2>, <6, 3, 2>, 0.2 txt001 trn001 }
object { sphere <-4, 1, 3>, 0.2 txt001 trn001 }
object { cylinder <-4, 1, 3>, <-3, 2, 1>, 0.2 txt001 trn001 }
object { sphere <-3, 1, 3>, 0.2 txt001 trn001 }
object { cylinder <-3, 1, 3>, <-3, 2, 2>, 0.2 txt001 trn001 }
object { sphere <-2, 1, 3>, 0.2 txt001 trn001 }
object { cylinder <-2, 1, 3>, <-1, 2, 3>, 0.2 txt001 trn001 }
object { sphere <-1, 1, 3>, 0.2 txt001 trn001 }
object { cylinder <-1, 1, 3>, <0, 2, 3>, 0.2 txt001 trn001 }
object { sphere <0, 1, 3>, 0.2 txt001 trn001 }
object { cylinder <0, 1, 3>, <1, 2, 0>, 0.2 txt001 trn001 }
object { sphere <1, 1, 3>, 0.2 txt001 trn001 }
object { cylinder <1, 1, 3>, <2, 2, 3>, 0.2 txt001 trn001 }
object { sphere <2, 1, 3>, 0.2 txt001 trn001 }
object { cylinder <2, 1, 3>, <2, 2, 0>, 0.2 txt001 trn001 }
object { sphere <3, 1, 3>, 0.2 txt001 trn001 }
object { cylinder <3, 1, 3>, <2, 2, 3>, 0.2 txt001 trn001 }
object { sphere <4, 1, 3>, 0.2 txt001 trn001 }
object { cylinder <4, 1, 3>, <3, 2, 3>, 0.2 txt001 trn001 }
object { sphere <5, 1, 3>, 0.2 txt001 trn001 }
object { cylinder <5, 1, 3>, <5, 2, 2>, 0.2 txt001 trn001 }
object { sphere <6, 1, 3>, 0.2 txt001 trn001 }
object { cylinder <6, 1, 3>, <5, 2, 1>, 0.2 txt001 trn001 }
object { sphere <-3, 2, 3>, 0.2 txt001 trn001 }
object { cylinder <-3, 2, 3>, <-2, 3, 1>, 0.2 txt001 trn001 }
object { sphere <-2, 2, 3>, 0.2 txt001 trn001 }
object { cylinder <-2, 2, 3>, <-1, 3, 3>, 0.2 txt001 trn001 }
object { sphere <-1, 2, 3>, 0.2 txt001 trn001 }
object { cylinder <-1, 2, 3>, <0, 3, 3>, 0.2 txt001 trn001 }
object { sphere <0, 2, 3>, 0.2 txt001 trn001 }
object { cylinder <0, 2, 3>, <-1, 2, 0>, 0.2 txt001 trn001 }
object { sphere <1, 2, 3>, 0.2 txt001 trn001 }
object { cylinder <1, 2, 3>, <1, 2, 1>, 0.2 txt001 trn001 }
object { sphere <2, 2, 3>, 0.2 txt001 trn001 }
object { cylinder <2, 2, 3>, <1, 3, 1>, 0.2 txt001 trn001 }
object { sphere <3, 2, 3>, 0.2 txt001 trn001 }
object { cylinder <3, 2, 3>, <2, 2, 3>, 0.2 txt001 trn001 }
object { sphere <4, 2, 3>, 0.2 txt001 trn001 }
object { cylinder <4, 2, 3>, <3, 2, 1>, 0.2 txt001 trn001 }
object { sphere <5, 2, 3>, 0.2 txt001 trn001 }
object { cylinder <5, 2, 3>, <4, 2, 0>, 0.2 txt001 trn001 }
object { sphere <6, 2, 3>, 0.2 txt001 trn001 }
object { cylinder <6, 2, 3>, <5, 2, 4>, 0.2 txt001 trn001 }
object { sphere <-3, 3, 3>, 0.2 txt001 trn001 }
object { cylinder <-3, 3, 3>, <-2, 4, 3>, 0.2 txt001 trn001 }
object { sphere <-2, 3, 3>, 0.2 txt001 trn001 }
object { cylinder <-2, 3, 3>, <-1, 2, 0>, 0.2 txt001 trn001 }
object { sphere <-1, 3, 3>, 0.2 txt001 trn001 }
object { cylinder <-1, 3, 3>, <-2, 2, 1>, 0.2 txt001 trn001 }
object { sphere <0, 3, 3>, 0.2 txt001 trn001 }
object { cylinder <0, 3, 3>, <1, 3, 1>, 0.2 txt001 trn001 }
object { sphere <1, 3, 3>, 0.2 txt001 trn001 }
object { cylinder <1, 3, 3>, <0, 2, 3>, 0.2 txt001 trn001 }
object { sphere <2, 3, 3>, 0.2 txt001 trn001 }
object { cylinder <2, 3, 3>, <2, 2, 2>, 0.2 txt001 trn001 }
object { sphere <3, 3, 3>, 0.2 txt001 trn001 }
object { cylinder <3, 3, 3>, <4, 2, 0>, 0.2 txt001 trn001 }
object { sphere <4, 3, 3>, 0.2 txt001 trn001 }
object { cylinder <4, 3, 3>, <3, 3, 3>, 0.2 txt001 trn001 }
object { sphere <5, 3, 3>, 0.2 txt001 trn001 }
object { cylinder <5, 3, 3>, <5, 2, 4>, 0.2 txt001 trn001 }
object { sphere <6, 3, 3>, 0.2 txt001 trn001 }
object { cylinder <6, 3, 3>, <5, 3, 3>, 0.2 txt001 trn001 }
object { sphere <7, 3, 3>, 0.2 txt001 trn001 }
object { cylinder <7, 3, 3>, <7, 4, 4>, 0.2 txt001 trn001 }
object { sphere <-3, 4, 3>, 0.2 txt001 trn001 }
object { cylinder <-3, 4, 3>, <-2, 4, 4>, 0.2 txt001 trn001 }
object { sphere <-2, 4, 3>, 0.2 txt001 trn001 }
object { cylinder <-2, 4, 3>, <-1, 3, 3>, 0.2 txt001 trn001 }
object { sphere <-1, 4, 3>, 0.2 txt001 trn001 }
object { cylinder <-1, 4, 3>, <0, 3, 3>, 0.2 txt001 trn001 }
object { sphere <0, 4, 3>, 0.2 txt001 trn001 }
object { cylinder <0, 4, 3>, <1, 3, 1>, 0.2 txt001 trn001 }
object { sphere <1, 4, 3>, 0.2 txt001 trn001 }
object { cylinder <1, 4, 3>, <2, 3, 1>, 0.2 txt001 trn001 }
object { sphere <2, 4, 3>, 0.2 txt001 trn001 }
object { cylinder <2, 4, 3>, <1, 3, 1>, 0.2 txt001 trn001 }
object { sphere <3, 4, 3>, 0.2 txt001 trn001 }
object { cylinder <3, 4, 3>, <3, 3, 3>, 0.2 txt001 trn001 }
object { sphere <4, 4, 3>, 0.2 txt001 trn001 }
object { cylinder <4, 4, 3>, <3, 3, 3>, 0.2 txt001 trn001 }
object { sphere <5, 4, 3>, 0.2 txt001 trn001 }
object { cylinder <5, 4, 3>, <6, 4, 6>, 0.2 txt001 trn001 }
object { sphere <-2, 5, 3>, 0.2 txt001 trn001 }
object { cylinder <-2, 5, 3>, <-1, 4, 3>, 0.2 txt001 trn001 }
object { sphere <-1, 5, 3>, 0.2 txt001 trn001 }
object { cylinder <-1, 5, 3>, <-1, 4, 2>, 0.2 txt001 trn001 }
object { sphere <0, 5, 3>, 0.2 txt001 trn001 }
object { cylinder <0, 5, 3>, <0, 4, 6>, 0.2 txt001 trn001 }
object { sphere <1, 5, 3>, 0.2 txt001 trn001 }
object { cylinder <1, 5, 3>, <2, 4, 3>, 0.2 txt001 trn001 }
object { sphere <2, 5, 3>, 0.2 txt001 trn001 }
object { cylinder <2, 5, 3>, <2, 4, 3>, 0.2 txt001 trn001 }
object { sphere <3, 5, 3>, 0.2 txt001 trn001 }
object { cylinder <3, 5, 3>, <3, 4, 3>, 0.2 txt001 trn001 }
object { sphere <-3, 2, 4>, 0.2 txt001 trn001 }
object { cylinder <-3, 2, 4>, <-2, 3, 1>, 0.2 txt001 trn001 }
object { sphere <-2, 2, 4>, 0.2 txt001 trn001 }
object { cylinder <-2, 2, 4>, <-2, 3, 4>, 0.2 txt001 trn001 }
object { sphere <-1, 2, 4>, 0.2 txt001 trn001 }
object { cylinder <-1, 2, 4>, <-1, 3, 2>, 0.2 txt001 trn001 }
object { sphere <0, 2, 4>, 0.2 txt001 trn001 }
object { cylinder <0, 2, 4>, <0, 3, 2>, 0.2 txt001 trn001 }
object { sphere <1, 2, 4>, 0.2 txt001 trn001 }
object { cylinder <1, 2, 4>, <1, 3, 1>, 0.2 txt001 trn001 }
object { sphere <2, 2, 4>, 0.2 txt001 trn001 }
object { cylinder <2, 2, 4>, <2, 3, 2>, 0.2 txt001 trn001 }
object { sphere <3, 2, 4>, 0.2 txt001 trn001 }
object { cylinder <3, 2, 4>, <4, 3, 4>, 0.2 txt001 trn001 }
object { sphere <4, 2, 4>, 0.2 txt001 trn001 }
object { cylinder <4, 2, 4>, <4, 3, 1>, 0.2 txt001 trn001 }
object { sphere <5, 2, 4>, 0.2 txt001 trn001 }
object { cylinder <5, 2, 4>, <4, 3, 1>, 0.2 txt001 trn001 }
object { sphere <7, 2, 4>, 0.2 txt001 trn001 }
object { cylinder <7, 2, 4>, <6, 3, 2>, 0.2 txt001 trn001 }
object { sphere <-2, 3, 4>, 0.2 txt001 trn001 }
object { cylinder <-2, 3, 4>, <-1, 3, 4>, 0.2 txt001 trn001 }
object { sphere <-1, 3, 4>, 0.2 txt001 trn001 }
object { cylinder <-1, 3, 4>, <0, 3, 3>, 0.2 txt001 trn001 }
object { sphere <0, 3, 4>, 0.2 txt001 trn001 }
object { cylinder <0, 3, 4>, <1, 3, 1>, 0.2 txt001 trn001 }
object { sphere <1, 3, 4>, 0.2 txt001 trn001 }
object { cylinder <1, 3, 4>, <0, 3, 5>, 0.2 txt001 trn001 }
object { sphere <2, 3, 4>, 0.2 txt001 trn001 }
object { cylinder <2, 3, 4>, <2, 4, 2>, 0.2 txt001 trn001 }
object { sphere <3, 3, 4>, 0.2 txt001 trn001 }
object { cylinder <3, 3, 4>, <2, 3, 1>, 0.2 txt001 trn001 }
object { sphere <4, 3, 4>, 0.2 txt001 trn001 }
object { cylinder <4, 3, 4>, <5, 4, 4>, 0.2 txt001 trn001 }
object { sphere <5, 3, 4>, 0.2 txt001 trn001 }
object { cylinder <5, 3, 4>, <4, 3, 2>, 0.2 txt001 trn001 }
object { sphere <6, 3, 4>, 0.2 txt001 trn001 }
object { cylinder <6, 3, 4>, <5, 3, 3>, 0.2 txt001 trn001 }
object { sphere <-3, 4, 4>, 0.2 txt001 trn001 }
object { cylinder <-3, 4, 4>, <-2, 3, 2>, 0.2 txt001 trn001 }
object { sphere <-2, 4, 4>, 0.2 txt001 trn001 }
object { cylinder <-2, 4, 4>, <-1, 4, 4>, 0.2 txt001 trn001 }
object { sphere <-1, 4, 4>, 0.2 txt001 trn001 }
object { cylinder <-1, 4, 4>, <0, 3, 4>, 0.2 txt001 trn001 }
object { sphere <0, 4, 4>, 0.2 txt001 trn001 }
object { cylinder <0, 4, 4>, <1, 3, 1>, 0.2 txt001 trn001 }
object { sphere <1, 4, 4>, 0.2 txt001 trn001 }
object { cylinder <1, 4, 4>, <2, 3, 2>, 0.2 txt001 trn001 }
object { sphere <2, 4, 4>, 0.2 txt001 trn001 }
object { cylinder <2, 4, 4>, <2, 3, 2>, 0.2 txt001 trn001 }
object { sphere <3, 4, 4>, 0.2 txt001 trn001 }
object { cylinder <3, 4, 4>, <3, 3, 4>, 0.2 txt001 trn001 }
object { sphere <4, 4, 4>, 0.2 txt001 trn001 }
object { cylinder <4, 4, 4>, <3, 3, 4>, 0.2 txt001 trn001 }
object { sphere <5, 4, 4>, 0.2 txt001 trn001 }
object { cylinder <5, 4, 4>, <6, 5, 6>, 0.2 txt001 trn001 }
object { sphere <7, 4, 4>, 0.2 txt001 trn001 }
object { cylinder <7, 4, 4>, <7, 5, 7>, 0.2 txt001 trn001 }
object { sphere <-4, 5, 4>, 0.2 txt001 trn001 }
object { cylinder <-4, 5, 4>, <-3, 4, 4>, 0.2 txt001 trn001 }
object { sphere <-3, 5, 4>, 0.2 txt001 trn001 }
object { cylinder <-3, 5, 4>, <-2, 5, 6>, 0.2 txt001 trn001 }
object { sphere <-2, 5, 4>, 0.2 txt001 trn001 }
object { cylinder <-2, 5, 4>, <-3, 4, 4>, 0.2 txt001 trn001 }
object { sphere <-1, 5, 4>, 0.2 txt001 trn001 }
object { cylinder <-1, 5, 4>, <-1, 5, 3>, 0.2 txt001 trn001 }
object { sphere <0, 5, 4>, 0.2 txt001 trn001 }
object { cylinder <0, 5, 4>, <-1, 4, 4>, 0.2 txt001 trn001 }
object { sphere <1, 5, 4>, 0.2 txt001 trn001 }
object { cylinder <1, 5, 4>, <1, 5, 3>, 0.2 txt001 trn001 }
object { sphere <2, 5, 4>, 0.2 txt001 trn001 }
object { cylinder <2, 5, 4>, <1, 4, 6>, 0.2 txt001 trn001 }
object { sphere <3, 5, 4>, 0.2 txt001 trn001 }
object { cylinder <3, 5, 4>, <4, 4, 4>, 0.2 txt001 trn001 }
object { sphere <5, 5, 4>, 0.2 txt001 trn001 }
object { cylinder <5, 5, 4>, <6, 5, 5>, 0.2 txt001 trn001 }
object { sphere <6, 5, 4>, 0.2 txt001 trn001 }
object { cylinder <6, 5, 4>, <5, 4, 4>, 0.2 txt001 trn001 }
object { sphere <7, 5, 4>, 0.2 txt001 trn001 }
object { cylinder <7, 5, 4>, <6, 5, 5>, 0.2 txt001 trn001 }
object { sphere <-2, 6, 4>, 0.2 txt001 trn001 }
object { cylinder <-2, 6, 4>, <-2, 5, 5>, 0.2 txt001 trn001 }
object { sphere <-1, 6, 4>, 0.2 txt001 trn001 }
object { cylinder <-1, 6, 4>, <-1, 5, 3>, 0.2 txt001 trn001 }
object { sphere <0, 6, 4>, 0.2 txt001 trn001 }
object { cylinder <0, 6, 4>, <0, 5, 5>, 0.2 txt001 trn001 }
object { sphere <1, 6, 4>, 0.2 txt001 trn001 }
object { cylinder <1, 6, 4>, <1, 5, 3>, 0.2 txt001 trn001 }
object { sphere <6, 6, 4>, 0.2 txt001 trn001 }
object { cylinder <6, 6, 4>, <6, 5, 4>, 0.2 txt001 trn001 }
object { sphere <-2, 3, 5>, 0.2 txt001 trn001 }
object { cylinder <-2, 3, 5>, <-1, 4, 2>, 0.2 txt001 trn001 }
object { sphere <-1, 3, 5>, 0.2 txt001 trn001 }
object { cylinder <-1, 3, 5>, <-1, 4, 2>, 0.2 txt001 trn001 }
object { sphere <0, 3, 5>, 0.2 txt001 trn001 }
object { cylinder <0, 3, 5>, <0, 4, 3>, 0.2 txt001 trn001 }
object { sphere <1, 3, 5>, 0.2 txt001 trn001 }
object { cylinder <1, 3, 5>, <0, 4, 5>, 0.2 txt001 trn001 }
object { sphere <2, 3, 5>, 0.2 txt001 trn001 }
object { cylinder <2, 3, 5>, <1, 4, 5>, 0.2 txt001 trn001 }
object { sphere <3, 3, 5>, 0.2 txt001 trn001 }
object { cylinder <3, 3, 5>, <2, 4, 3>, 0.2 txt001 trn001 }
object { sphere <4, 3, 5>, 0.2 txt001 trn001 }
object { cylinder <4, 3, 5>, <4, 4, 4>, 0.2 txt001 trn001 }
object { sphere <6, 3, 5>, 0.2 txt001 trn001 }
object { cylinder <6, 3, 5>, <5, 4, 2>, 0.2 txt001 trn001 }
object { sphere <-2, 4, 5>, 0.2 txt001 trn001 }
object { cylinder <-2, 4, 5>, <-1, 4, 5>, 0.2 txt001 trn001 }
object { sphere <-1, 4, 5>, 0.2 txt001 trn001 }
object { cylinder <-1, 4, 5>, <-1, 4, 2>, 0.2 txt001 trn001 }
object { sphere <0, 4, 5>, 0.2 txt001 trn001 }
object { cylinder <0, 4, 5>, <1, 4, 5>, 0.2 txt001 trn001 }
object { sphere <1, 4, 5>, 0.2 txt001 trn001 }
object { cylinder <1, 4, 5>, <1, 4, 4>, 0.2 txt001 trn001 }
object { sphere <2, 4, 5>, 0.2 txt001 trn001 }
object { cylinder <2, 4, 5>, <1, 4, 4>, 0.2 txt001 trn001 }
object { sphere <3, 4, 5>, 0.2 txt001 trn001 }
object { cylinder <3, 4, 5>, <2, 5, 5>, 0.2 txt001 trn001 }
object { sphere <4, 4, 5>, 0.2 txt001 trn001 }
object { cylinder <4, 4, 5>, <4, 4, 2>, 0.2 txt001 trn001 }
object { sphere <5, 4, 5>, 0.2 txt001 trn001 }
object { cylinder <5, 4, 5>, <5, 4, 4>, 0.2 txt001 trn001 }
object { sphere <6, 4, 5>, 0.2 txt001 trn001 }
object { cylinder <6, 4, 5>, <7, 5, 5>, 0.2 txt001 trn001 }
object { sphere <-3, 5, 5>, 0.2 txt001 trn001 }
object { cylinder <-3, 5, 5>, <-3, 4, 6>, 0.2 txt001 trn001 }
object { sphere <-2, 5, 5>, 0.2 txt001 trn001 }
object { cylinder <-2, 5, 5>, <-1, 4, 5>, 0.2 txt001 trn001 }
object { sphere <-1, 5, 5>, 0.2 txt001 trn001 }
object { cylinder <-1, 5, 5>, <-2, 6, 5>, 0.2 txt001 trn001 }
object { sphere <0, 5, 5>, 0.2 txt001 trn001 }
object { cylinder <0, 5, 5>, <1, 4, 3>, 0.2 txt001 trn001 }
object { sphere <1, 5, 5>, 0.2 txt001 trn001 }
object { cylinder <1, 5, 5>, <2, 4, 3>, 0.2 txt001 trn001 }
object { sphere <2, 5, 5>, 0.2 txt001 trn001 }
object { cylinder <2, 5, 5>, <1, 4, 2>, 0.2 txt001 trn001 }
object { sphere <3, 5, 5>, 0.2 txt001 trn001 }
object { cylinder <3, 5, 5>, <4, 4, 3>, 0.2 txt001 trn001 }
object { sphere <5, 5, 5>, 0.2 txt001 trn001 }
object { cylinder <5, 5, 5>, <6, 6, 7>, 0.2 txt001 trn001 }
object { sphere <6, 5, 5>, 0.2 txt001 trn001 }
object { cylinder <6, 5, 5>, <7, 6, 7>, 0.2 txt001 trn001 }
object { sphere <7, 5, 5>, 0.2 txt001 trn001 }
object { cylinder <7, 5, 5>, <7, 6, 7>, 0.2 txt001 trn001 }
object { sphere <-2, 6, 5>, 0.2 txt001 trn001 }
object { cylinder <-2, 6, 5>, <-1, 5, 3>, 0.2 txt001 trn001 }
object { sphere <-1, 6, 5>, 0.2 txt001 trn001 }
object { cylinder <-1, 6, 5>, <-1, 5, 5>, 0.2 txt001 trn001 }
object { sphere <0, 6, 5>, 0.2 txt001 trn001 }
object { cylinder <0, 6, 5>, <-1, 5, 5>, 0.2 txt001 trn001 }
object { sphere <1, 6, 5>, 0.2 txt001 trn001 }
object { cylinder <1, 6, 5>, <1, 5, 3>, 0.2 txt001 trn001 }
object { sphere <3, 6, 5>, 0.2 txt001 trn001 }
object { cylinder <3, 6, 5>, <2, 5, 3>, 0.2 txt001 trn001 }
object { sphere <5, 6, 5>, 0.2 txt001 trn001 }
object { cylinder <5, 6, 5>, <6, 6, 4>, 0.2 txt001 trn001 }
object { sphere <6, 6, 5>, 0.2 txt001 trn001 }
object { cylinder <6, 6, 5>, <6, 5, 5>, 0.2 txt001 trn001 }
object { sphere <7, 6, 5>, 0.2 txt001 trn001 }
object { cylinder <7, 6, 5>, <6, 6, 5>, 0.2 txt001 trn001 }
object { sphere <-1, 7, 5>, 0.2 txt001 trn001 }
object { cylinder <-1, 7, 5>, <-1, 6, 4>, 0.2 txt001 trn001 }
object { sphere <0, 7, 5>, 0.2 txt001 trn001 }
object { cylinder <0, 7, 5>, <0, 6, 6>, 0.2 txt001 trn001 }
object { sphere <6, 7, 5>, 0.2 txt001 trn001 }
object { cylinder <6, 7, 5>, <6, 6, 5>, 0.2 txt001 trn001 }
object { sphere <7, 7, 5>, 0.2 txt001 trn001 }
object { cylinder <7, 7, 5>, <6, 6, 5>, 0.2 txt001 trn001 }
object { sphere <-3, 4, 6>, 0.2 txt001 trn001 }
object { cylinder <-3, 4, 6>, <-2, 5, 6>, 0.2 txt001 trn001 }
object { sphere <-2, 4, 6>, 0.2 txt001 trn001 }
object { cylinder <-2, 4, 6>, <-1, 5, 4>, 0.2 txt001 trn001 }
object { sphere <-1, 4, 6>, 0.2 txt001 trn001 }
object { cylinder <-1, 4, 6>, <-1, 5, 5>, 0.2 txt001 trn001 }
object { sphere <0, 4, 6>, 0.2 txt001 trn001 }
object { cylinder <0, 4, 6>, <1, 5, 3>, 0.2 txt001 trn001 }
object { sphere <1, 4, 6>, 0.2 txt001 trn001 }
object { cylinder <1, 4, 6>, <0, 5, 4>, 0.2 txt001 trn001 }
object { sphere <4, 4, 6>, 0.2 txt001 trn001 }
object { cylinder <4, 4, 6>, <5, 5, 6>, 0.2 txt001 trn001 }
object { sphere <5, 4, 6>, 0.2 txt001 trn001 }
object { cylinder <5, 4, 6>, <5, 5, 4>, 0.2 txt001 trn001 }
object { sphere <6, 4, 6>, 0.2 txt001 trn001 }
object { cylinder <6, 4, 6>, <6, 5, 6>, 0.2 txt001 trn001 }
object { sphere <-3, 5, 6>, 0.2 txt001 trn001 }
object { cylinder <-3, 5, 6>, <-2, 5, 4>, 0.2 txt001 trn001 }
object { sphere <-2, 5, 6>, 0.2 txt001 trn001 }
object { cylinder <-2, 5, 6>, <-1, 6, 6>, 0.2 txt001 trn001 }
object { sphere <-1, 5, 6>, 0.2 txt001 trn001 }
object { cylinder <-1, 5, 6>, <-2, 5, 4>, 0.2 txt001 trn001 }
object { sphere <0, 5, 6>, 0.2 txt001 trn001 }
object { cylinder <0, 5, 6>, <1, 5, 5>, 0.2 txt001 trn001 }
object { sphere <1, 5, 6>, 0.2 txt001 trn001 }
object { cylinder <1, 5, 6>, <0, 5, 6>, 0.2 txt001 trn001 }
object { sphere <5, 5, 6>, 0.2 txt001 trn001 }
object { cylinder <5, 5, 6>, <5, 6, 6>, 0.2 txt001 trn001 }
object { sphere <6, 5, 6>, 0.2 txt001 trn001 }
object { cylinder <6, 5, 6>, <6, 6, 6>, 0.2 txt001 trn001 }
object { sphere <7, 5, 6>, 0.2 txt001 trn001 }
object { cylinder <7, 5, 6>, <7, 6, 7>, 0.2 txt001 trn001 }
object { sphere <-3, 6, 6>, 0.2 txt001 trn001 }
object { cylinder <-3, 6, 6>, <-2, 6, 4>, 0.2 txt001 trn001 }
object { sphere <-2, 6, 6>, 0.2 txt001 trn001 }
object { cylinder <-2, 6, 6>, <-1, 5, 3>, 0.2 txt001 trn001 }
object { sphere <-1, 6, 6>, 0.2 txt001 trn001 }
object { cylinder <-1, 6, 6>, <-1, 5, 5>, 0.2 txt001 trn001 }
object { sphere <0, 6, 6>, 0.2 txt001 trn001 }
object { cylinder <0, 6, 6>, <1, 5, 3>, 0.2 txt001 trn001 }
object { sphere <1, 6, 6>, 0.2 txt001 trn001 }
object { cylinder <1, 6, 6>, <1, 5, 4>, 0.2 txt001 trn001 }
object { sphere <5, 6, 6>, 0.2 txt001 trn001 }
object { cylinder <5, 6, 6>, <6, 7, 6>, 0.2 txt001 trn001 }
object { sphere <6, 6, 6>, 0.2 txt001 trn001 }
object { cylinder <6, 6, 6>, <7, 7, 6>, 0.2 txt001 trn001 }
object { sphere <7, 6, 6>, 0.2 txt001 trn001 }
object { cylinder <7, 6, 6>, <7, 7, 6>, 0.2 txt001 trn001 }
object { sphere <-1, 7, 6>, 0.2 txt001 trn001 }
object { cylinder <-1, 7, 6>, <0, 7, 5>, 0.2 txt001 trn001 }
object { sphere <0, 7, 6>, 0.2 txt001 trn001 }
object { cylinder <0, 7, 6>, <0, 6, 6>, 0.2 txt001 trn001 }
object { sphere <2, 7, 6>, 0.2 txt001 trn001 }
object { cylinder <2, 7, 6>, <1, 6, 6>, 0.2 txt001 trn001 }
object { sphere <5, 7, 6>, 0.2 txt001 trn001 }
object { cylinder <5, 7, 6>, <6, 7, 7>, 0.2 txt001 trn001 }
object { sphere <6, 7, 6>, 0.2 txt001 trn001 }
object { cylinder <6, 7, 6>, <7, 7, 6>, 0.2 txt001 trn001 }
object { sphere <7, 7, 6>, 0.2 txt001 trn001 }
object { cylinder <7, 7, 6>, <7, 7, 7>, 0.2 txt001 trn001 }
object { sphere <-1, 5, 7>, 0.2 txt001 trn001 }
object { cylinder <-1, 5, 7>, <-2, 6, 5>, 0.2 txt001 trn001 }
object { sphere <5, 5, 7>, 0.2 txt001 trn001 }
object { cylinder <5, 5, 7>, <6, 6, 4>, 0.2 txt001 trn001 }
object { sphere <6, 5, 7>, 0.2 txt001 trn001 }
object { cylinder <6, 5, 7>, <7, 6, 7>, 0.2 txt001 trn001 }
object { sphere <7, 5, 7>, 0.2 txt001 trn001 }
object { cylinder <7, 5, 7>, <6, 6, 5>, 0.2 txt001 trn001 }
object { sphere <-1, 6, 7>, 0.2 txt001 trn001 }
object { cylinder <-1, 6, 7>, <0, 6, 6>, 0.2 txt001 trn001 }
object { sphere <0, 6, 7>, 0.2 txt001 trn001 }
object { cylinder <0, 6, 7>, <1, 6, 5>, 0.2 txt001 trn001 }
object { sphere <5, 6, 7>, 0.2 txt001 trn001 }
object { cylinder <5, 6, 7>, <6, 7, 7>, 0.2 txt001 trn001 }
object { sphere <6, 6, 7>, 0.2 txt001 trn001 }
object { cylinder <6, 6, 7>, <6, 6, 5>, 0.2 txt001 trn001 }
object { sphere <7, 6, 7>, 0.2 txt001 trn001 }
object { cylinder <7, 6, 7>, <7, 7, 7>, 0.2 txt001 trn001 }
object { sphere <0, 7, 7>, 0.2 txt001 trn001 }
object { cylinder <0, 7, 7>, <-1, 6, 7>, 0.2 txt001 trn001 }
object { sphere <4, 7, 7>, 0.2 txt001 trn001 }
object { cylinder <4, 7, 7>, <5, 7, 7>, 0.2 txt001 trn001 }
object { sphere <5, 7, 7>, 0.2 txt001 trn001 }
object { cylinder <5, 7, 7>, <5, 7, 6>, 0.2 txt001 trn001 }
object { sphere <6, 7, 7>, 0.2 txt001 trn001 }
object { sphere <7, 7, 7>, 0.2 txt001 trn001 }
object { cylinder <7, 7, 7>, <0, 0, -1>, 0.2 txt001 trn001 }
