polyray bezier0.pi  -o bezier0.tga
polyray box1.pi     -o box1.tga
polyray bsphere.pi  -o bsphere.tga
polyray cone.pi     -o cone.tga
polyray cones.pi    -o cones.tga
polyray csg1.pi     -o csg1.tga
polyray csg2.pi     -o csg2.tga
polyray csg3.pi     -o csg3.tga
polyray cylinder.pi -o cylinder.tga
polyray disc.pi     -o disc.tga
polyray discs.pi    -o discs.tga
polyray msphere.pi  -o marble.tga
polyray parabol.pi  -o parabol.tga
polyray polygon.pi  -o polygon.tga
polyray shear.pi    -o shear.tga
polyray sphere.pi   -o sphere.tga
polyray torus.pi    -o torus.tga
