define shiny_red
texture {
   surface {
      ambient red, 0.2
      diffuse red, 0.6
      specular white, 0.8
      microfacet Reitz 10
      }
   }

define shiny_green
texture {
   surface {
      ambient green, 0.2
      diffuse green, 0.6
      specular white, 0.8
      microfacet Reitz 10
      }
   }

define shiny_blue
texture {
   surface {
      ambient blue, 0.2
      diffuse blue, 0.6
      specular white, 0.8
      microfacet Reitz 10
      }
   }

define shiny_cyan
texture {
   surface {
      ambient cyan, 0.2
      diffuse cyan, 0.6
      specular white, 0.8
      microfacet Reitz 10
      }
   }

define shiny_yellow
texture {
   surface {
      ambient yellow, 0.2
      diffuse yellow, 0.6
      specular white, 0.8
      microfacet Reitz 10
      }
   }

define shiny_magenta
texture {
   surface {
      ambient magenta, 0.2
      diffuse magenta, 0.6
      specular white, 0.8
      microfacet Reitz 10
      }
   }

define shiny_gold
texture {
   surface {
      ambient gold, 0.2
      diffuse gold, 0.6
      specular white, 0.8
      microfacet Reitz 10
      }
   }

define shiny_salmon
texture {
   surface {
      ambient salmon, 0.2
      diffuse salmon, 0.6
      specular white, 0.8
      microfacet Reitz 10
      }
   }

define shiny_orange
texture {
   surface {
      ambient orange, 0.2
      diffuse orange, 0.6
      specular white, 0.8
      microfacet Reitz 10
      }
   }

define shiny_coral
texture {
   surface {
      ambient coral, 0.2
      diffuse coral, 0.6
      specular white, 0.8
      microfacet Reitz 10
      }
   }

